### ISSUE TITLE
Applying GRU-D on own data

### ISSUE THREAD

**Issue by edwinlebreton** [PeterChe1990/GRU-D#3]
Hi,

With my research lab we are trying to apply GRU-D to our health metrical data.
Unfortunately, when running the Run script, starting the first epoch, we have the following error apparently coming from the data_handler:

<img width="754" alt="Capture d’écran 2020-02-27 à 15 33 08" src="https://user-images.githubusercontent.com/25383088/75454917-84f6c800-5976-11ea-995e-d4773797b02a.png">
<img width="736" alt="Capture d’écran 2020-02-27 à 15 33 20" src="https://user-images.githubusercontent.com/25383088/75454943-8d4f0300-5976-11ea-9f0a-cb931cafda90.png">

Have you ever seen something similar coming from this part of the code ?

Sorry if our issue looks basic, we are Data Science beginners students.

Thanks

**Comment by PeterChe1990** [comment]
The error comes from Line 128/129 in data_hanlder.py. Maybe your own data have not been formatted in the way mentioned in the [README.md:](https://github.com/PeterChe1990/GRU-D/blob/master/README.md#running-on-your-own-data) 

> In `[WD]/data/${dataset_name}/data.npz`, there are input, masking, timestamp, label_${label_name}. Each of them is of the shape (n_samples, ...)
In `[WD]/data/${dataset_name}/fold.npz`, there are `fold_${label_name}`, `mean_${label_name}`, `std_${label_name}`. Each of them is of the shape (k_fold, 3, ...), for train/validation/test sets in k-fold cross validation.

Also, it seems that Line 128 was modified incorrectly: 
`inputs = [self._data[s][batch_fold] for s in ['input', 'masking', 'timestamp']]` should not be `self._data[s][0]`, otherwise the data generator would always generate the first input sample from the dataset.
